version: "3"

services:

  postgres:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - awesome
  
  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "1502:80"
    tty: true
    env_file:
      - .env
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    tty: true 
    networks:
      - awesome

volumes:
  postgres:
  pgadmin:

networks:
  awesome:
    driver: bridge